# Generated by Django 5.2.9 on 2025-12-14 18:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_failed_login_attempts_user_lockout_until'),
        ('services', '0007_delete_specialoffer'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department assignment for service_head and team_member roles', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='members', to='services.department'),
        ),
    ]
