# Generated by Django 5.2.9 on 2025-12-17 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, help_text='Job title/role for team members (e.g., Voice-over Artist, Frontend Developer)', max_length=100, null=True),
        ),
    ]
