# Generated by Django 6.0 on 2025-12-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='client_id',
            new_name='client',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='pricing_plan_id',
            new_name='pricing_plan',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='service_id',
            new_name='service',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='review',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('revision', 'Revision')], default='pending', max_length=20),
        ),
    ]
