# Generated by Django 6.0 on 2025-12-06 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_rename_client_id_order_client_and_more'),
        ('services', '0002_remove_pricingplan_service_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pricing_plan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='services.pricecard'),
        ),
    ]
