# Generated by Django 5.2.9 on 2025-12-10 18:14

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_pricing_plan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['order_index', '-created_at']},
        ),
        migrations.AddField(
            model_name='offer',
            name='button_text',
            field=models.CharField(default='Claim Offer', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='button_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='conditions',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_code',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='features',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='offer',
            name='gradient_colors',
            field=models.CharField(default='from-red-500 to-orange-500', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='icon_name',
            field=models.CharField(default='FiTag', max_length=50),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_limited_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='order_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='offer',
            name='short_description',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
