# Generated by Django 5.2.9 on 2025-12-11 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_offer_options_offer_button_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.RenameField(
            model_name='offer',
            old_name='order_index',
            new_name='priority',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='discount_percent',
        ),
        migrations.RemoveField(
            model_name='offer',
            name='is_limited_time',
        ),
        migrations.AddField(
            model_name='offer',
            name='cta_link',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='offer',
            name='cta_text',
            field=models.CharField(default='Claim Offer', max_length=100),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_type',
            field=models.CharField(choices=[('percent', 'Percentage'), ('flat', 'Flat Amount')], default='percent', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=20, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='offer',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='offers/'),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('seasonal', 'Seasonal Offer'), ('limited', 'Limited Time'), ('bundle', 'Bundle Offer'), ('launch', 'Launch Offer')], default='seasonal', max_length=20),
        ),
        migrations.AddField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='terms',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='offer',
            name='button_text',
            field=models.CharField(blank=True, default='Claim Offer', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='gradient_colors',
            field=models.CharField(blank=True, default='from-red-500 to-orange-500', max_length=100),
        ),
        migrations.AlterField(
            model_name='offer',
            name='icon_name',
            field=models.CharField(blank=True, default='FiTag', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
