# Generated by Django 5.2.9 on 2025-12-11 17:14

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_alter_offer_options_and_more'),
        ('services', '0007_delete_specialoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='offer',
            options={'ordering': ['-priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='offer',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Admin who approved the offer.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created the offer (admin or team head).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_offers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='offer',
            name='created_by_department',
            field=models.ForeignKey(blank=True, help_text='Optional snapshot of department for the creator (useful for team-head scoping).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offers_created', to='services.department'),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='is_limited_time',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='services',
            field=models.ManyToManyField(blank=True, help_text='Services covered by this offer (can be multiple).', related_name='offers', to='services.service'),
        ),
        migrations.AddField(
            model_name='offer',
            name='slug',
            field=models.SlugField(blank=True, max_length=220, unique=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='conditions',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='offer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='features',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='offer',
            name='icon_name',
            field=models.CharField(blank=True, default='tag', max_length=50),
        ),
        migrations.AlterField(
            model_name='offer',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='priority',
            field=models.IntegerField(default=0, help_text='Higher priority shows earlier in ordered lists'),
        ),
        migrations.AlterField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='offer',
            name='valid_to',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_active'], name='offers_is_acti_5de943_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_featured'], name='offers_is_feat_efe348_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['is_approved'], name='offers_is_appr_cbcdfb_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['valid_to'], name='offers_valid_t_8c93f0_idx'),
        ),
    ]
