# Generated by Django 5.2.9 on 2025-12-12 17:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_client_email_alter_order_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
    ]
