# Generated by Django 5.2.9 on 2025-12-12 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_order_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='progress',
        ),
    ]
