# Generated by Django 5.2.9 on 2025-12-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_order_progress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliverables',
            field=models.JSONField(blank=True, default=list, help_text='List of Cloudinary URLs for final deliverable files'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='status_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('estimation_sent', 'Estimation Sent'), ('in_progress', 'In Progress'), ('25_done', '25% Complete'), ('50_done', '50% Complete'), ('75_done', '75% Complete'), ('ready_for_delivery', 'Ready for Delivery'), ('delivered', 'Delivered'), ('payment_pending', 'Payment Pending'), ('payment_done', 'Payment Done'), ('closed', 'Closed')], default='pending', max_length=30),
        ),
    ]
