# Generated by Django 5.2.9 on 2025-12-13 12:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_serviceformsubmission_order'),
        ('orders', '0011_estimation_invoice_orderstatushistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='form_submission',
            field=models.ForeignKey(blank=True, help_text='Reference to form submission if order was created via form', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_order', to='forms.serviceformsubmission'),
        ),
        migrations.AddField(
            model_name='order',
            name='price_card_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Selected price plan price', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='price_card_title',
            field=models.CharField(blank=True, help_text='Selected price plan title', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='total_paid',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total amount paid so far (for partial payments)', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='order',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='Client WhatsApp number', max_length=20, null=True),
        ),
    ]
