# Generated by Django 5.2.9 on 2025-12-14 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_order_form_submission_order_price_card_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
