# Generated by Django 5.2.9 on 2025-12-16 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_order_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='pdf_public_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_public_id',
        ),
        migrations.AddField(
            model_name='estimation',
            name='pdf_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file_id',
            field=models.CharField(blank=True, help_text='Google Drive file ID', max_length=255),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Google Drive download URL for generated PDF'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Google Drive download URL for generated PDF'),
        ),
    ]
