# Generated by Django 5.2.9 on 2025-12-16 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_remove_estimation_pdf_public_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='pdf_file_id',
        ),
        migrations.RemoveField(
            model_name='invoice',
            name='pdf_file_id',
        ),
        migrations.AddField(
            model_name='estimation',
            name='pdf_file_path',
            field=models.CharField(blank=True, help_text='Dropbox file path', max_length=500),
        ),
        migrations.AddField(
            model_name='invoice',
            name='pdf_file_path',
            field=models.CharField(blank=True, help_text='Dropbox file path', max_length=500),
        ),
        migrations.AlterField(
            model_name='estimation',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Dropbox download URL for generated PDF'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='pdf_url',
            field=models.URLField(blank=True, help_text='Dropbox download URL for generated PDF'),
        ),
    ]
