# Generated by Django 5.2.9 on 2025-12-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_alter_invoice_invoice_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='offer_category',
            field=models.CharField(choices=[('regular', 'Regular Offer'), ('special', 'Special Offer')], default='regular', help_text='Regular offers: single service. Special offers: multiple services.', max_length=20),
        ),
    ]
