# Generated by Django 5.2.9 on 2025-12-18 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_offer_offer_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='imageURL',
            field=models.URLField(blank=True, help_text='Cloudinary image URL', max_length=500, null=True),
        ),
    ]
