# Generated by Django 5.2.9 on 2025-12-20 16:20
# Modified to properly handle existing data

import uuid
from django.db import migrations, models


def generate_unique_uuids(apps, schema_editor):
    """Generate unique UUIDs for all existing orders"""
    Order = apps.get_model('orders', 'Order')
    for order in Order.objects.all():
        order.uuid = uuid.uuid4()
        order.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_offer_imageurl'),
    ]

    operations = [
        # Step 1: Add UUID field without unique constraint
        migrations.AddField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        # Step 2: Populate UUIDs for existing records
        migrations.RunPython(generate_unique_uuids, reverse_code=migrations.RunPython.noop),
        # Step 3: Make UUID non-nullable and unique
        migrations.AlterField(
            model_name='order',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
