# Generated by Django 5.2.9 on 2025-12-31 14:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_order_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimation',
            name='valid_until',
        ),
        migrations.AddField(
            model_name='estimation',
            name='client_address',
            field=models.TextField(blank=True, help_text="Client's full address for estimation PDF"),
        ),
        migrations.AddField(
            model_name='estimation',
            name='client_phone',
            field=models.CharField(blank=True, help_text="Client's phone number for estimation PDF", max_length=20),
        ),
        migrations.AddField(
            model_name='estimation',
            name='delivery_date',
            field=models.DateField(blank=True, help_text='Expected delivery date for the project', null=True),
        ),
        migrations.AddField(
            model_name='estimation',
            name='department_head_email',
            field=models.EmailField(blank=True, help_text='Email of department head', max_length=254),
        ),
        migrations.AddField(
            model_name='estimation',
            name='department_head_name',
            field=models.CharField(blank=True, help_text='Name of department head sending the estimation', max_length=255),
        ),
        migrations.AddField(
            model_name='estimation',
            name='department_head_phone',
            field=models.CharField(blank=True, help_text='Phone number of department head', max_length=20),
        ),
        migrations.AddField(
            model_name='estimation',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Discount amount to be deducted from subtotal', max_digits=12, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='invoice',
            name='chairperson_name',
            field=models.CharField(default='Omkar Vaijanath Kangule', help_text='Name of chairperson for signature', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_address',
            field=models.TextField(blank=True, help_text="Client's full address for invoice PDF"),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_phone',
            field=models.CharField(blank=True, help_text="Client's phone number for invoice PDF", max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='department_head_email',
            field=models.EmailField(blank=True, help_text='Email of department head', max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='department_head_name',
            field=models.CharField(blank=True, help_text='Name of department head sending the invoice', max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='department_head_phone',
            field=models.CharField(blank=True, help_text='Phone number of department head', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='referral_policies',
            field=models.TextField(blank=True, help_text='Referral policies and team notes'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='vice_chairperson_name',
            field=models.CharField(default='Rahul Vishnu Bhatambare', help_text='Name of vice-chairperson for signature', max_length=255),
        ),
    ]
