# Generated by Django 5.2.9 on 2025-12-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_remove_estimation_valid_until_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimation',
            name='client_email',
            field=models.EmailField(blank=True, help_text="Client's email for estimation PDF", max_length=254),
        ),
        migrations.AddField(
            model_name='estimation',
            name='client_name',
            field=models.CharField(blank=True, help_text="Client's full name for estimation PDF", max_length=255),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_email',
            field=models.EmailField(blank=True, help_text="Client's email for invoice PDF", max_length=254),
        ),
        migrations.AddField(
            model_name='invoice',
            name='client_name',
            field=models.CharField(blank=True, help_text="Client's full name for invoice PDF", max_length=255),
        ),
    ]
