# Generated by Django 5.2.9 on 2025-12-31 18:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_estimation_client_email_estimation_client_name_and_more'),
        ('portfolio', '0007_alter_portfolioproject_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='portfolio_project',
            field=models.ForeignKey(blank=True, help_text='The portfolio project that inspired this order', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspired_orders', to='portfolio.portfolioproject'),
        ),
    ]
