# Generated by Django 5.2.9 on 2026-04-05 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0022_order_portfolio_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='price_card_price',
        ),
    ]
