# Generated by Django 6.0 on 2025-12-08 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
        ('services', '0004_alter_department_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactsubmission',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_requests', to='services.service'),
        ),
    ]
