# Generated by Django 6.0 on 2025-12-06 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='portfolioproject',
            old_name='service_id',
            new_name='service',
        ),
    ]
