# Generated by Django 6.0 on 2025-12-07 08:13

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_rename_service_id_portfolioproject_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of Cloudinary URLs for project images'),
        ),
    ]
