# Generated by Django 6.0 on 2025-12-08 15:01

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_portfolioproject_featured_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolioproject',
            name='video',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='video'),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='featured_image',
            field=cloudinary.models.CloudinaryField(default=0, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='images',
            field=models.JSONField(blank=True, default=list, help_text='List of Cloudinary URLs'),
        ),
    ]
