# Generated by Django 6.0 on 2025-12-08 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_portfolioproject_video_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolioproject',
            name='featured_image',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='images',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='portfolioproject',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
