# Generated by Django 6.0 on 2025-12-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_alter_portfolioproject_featured_image_and_more'),
        ('services', '0006_pricingcomparison_specialoffer_pricingplan'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseStudy',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField()),
                ('full_description', models.TextField(blank=True)),
                ('client_name', models.CharField(max_length=255)),
                ('client_logo', models.URLField(blank=True)),
                ('category', models.CharField(max_length=100)),
                ('featured_image', models.URLField()),
                ('gallery_images', models.JSONField(blank=True, default=list)),
                ('technologies', models.JSONField(blank=True, default=list)),
                ('duration', models.CharField(max_length=100)),
                ('results', models.TextField()),
                ('metrics', models.JSONField(blank=True, default=list)),
                ('challenges', models.JSONField(blank=True, default=list)),
                ('solutions', models.JSONField(blank=True, default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service')),
                ('testimonial', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='testimonials.testimonial')),
            ],
            options={
                'verbose_name_plural': 'Case Studies',
                'db_table': 'case_studies',
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
    ]
