# Generated by Django 5.2.9 on 2025-12-30 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0006_casestudy'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioproject',
            options={'ordering': ['priority', '-created_at']},
        ),
        migrations.AddField(
            model_name='portfolioproject',
            name='priority',
            field=models.PositiveIntegerField(default=999, help_text='Display priority (lower number = higher priority)'),
        ),
    ]
