# Generated by Django 6.0 on 2025-12-06 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricingplan',
            name='service',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['department', 'title']},
        ),
        migrations.RenameField(
            model_name='service',
            old_name='long_desc',
            new_name='long_description',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='short_desc',
            new_name='short_description',
        ),
        migrations.AddField(
            model_name='service',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='services/logos/'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='departments/logos/')),
                ('short_description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team_head', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='departments_managed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'departments',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='service',
            name='department',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='services', to='services.department'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PriceCard',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(choices=[('basic', 'Basic'), ('medium', 'Medium'), ('premium', 'Premium')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('revisions', models.PositiveIntegerField(default=1)),
                ('description', models.TextField(blank=True)),
                ('features', models.JSONField(blank=True, null=True)),
                ('delivery_days', models.PositiveIntegerField(default=7)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cards', to='services.department')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_cards', to='services.service')),
            ],
            options={
                'db_table': 'price_cards',
            },
        ),
    ]
