# Generated by Django 6.0 on 2025-12-06 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_order_pricing_plan'),
        ('services', '0002_remove_pricingplan_service_alter_service_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PricingPlan',
        ),
        migrations.AlterUniqueTogether(
            name='pricecard',
            unique_together={('title', 'service')},
        ),
    ]
