# Generated by Django 6.0 on 2025-12-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_pricingplan_alter_pricecard_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
