# Generated by Django 6.0 on 2025-12-08 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_alter_department_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='logo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
