# Generated by Django 6.0 on 2025-12-09 06:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_alter_service_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='PricingComparison',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('feature', models.CharField(max_length=255)),
                ('basic', models.CharField(max_length=255)),
                ('growth', models.CharField(max_length=255)),
                ('enterprise', models.CharField(max_length=255)),
                ('is_important', models.BooleanField(default=False)),
                ('order_index', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'pricing_comparisons',
                'ordering': ['order_index'],
            },
        ),
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('short_description', models.CharField(max_length=200)),
                ('icon_name', models.CharField(default='star', max_length=50)),
                ('features', models.JSONField(blank=True, default=list)),
                ('discount_percentage', models.IntegerField(blank=True, null=True)),
                ('discount_code', models.CharField(blank=True, max_length=50)),
                ('valid_from', models.DateTimeField()),
                ('valid_until', models.DateTimeField()),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_limited_time', models.BooleanField(default=False)),
                ('conditions', models.JSONField(blank=True, default=list)),
                ('gradient_colors', models.CharField(default='from-red-500 to-orange-500', max_length=100)),
                ('button_text', models.CharField(default='Claim Offer', max_length=50)),
                ('button_url', models.URLField(blank=True)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'special_offers',
                'ordering': ['order_index', '-is_featured'],
            },
        ),
        migrations.CreateModel(
            name='PricingPlan',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=50)),
                ('price_numeric', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('billing_period', models.CharField(choices=[('monthly', 'Monthly'), ('yearly', 'Yearly'), ('one_time', 'One Time')], default='one_time', max_length=20)),
                ('is_popular', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('features', models.JSONField(blank=True, default=list)),
                ('gradient_colors', models.CharField(default='from-blue-500 to-purple-500', max_length=100)),
                ('button_text', models.CharField(default='Get Started', max_length=50)),
                ('order_index', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pricing_plans', to='services.service')),
            ],
            options={
                'db_table': 'pricing_plans',
                'ordering': ['order_index', 'price_numeric'],
            },
        ),
    ]
