# Generated by Django 5.2.9 on 2025-12-11 08:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_pricingcomparison_specialoffer_pricingplan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SpecialOffer',
        ),
    ]
