# Generated by Django 5.2.9 on 2025-12-17 05:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_delete_specialoffer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='team_members',
            field=models.ManyToManyField(blank=True, help_text='Team members assigned to this service', limit_choices_to={'role': 'team_member'}, related_name='assigned_services', to=settings.AUTH_USER_MODEL),
        ),
    ]
