# Generated by Django 5.2.9 on 2025-12-28 11:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_service_team_members'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['is_active'], name='departments_is_acti_a777bd_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['created_at'], name='departments_created_8afb0d_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['is_active'], name='services_is_acti_b1f5d3_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['department', 'is_active'], name='services_departm_9de788_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['created_at'], name='services_created_22da02_idx'),
        ),
    ]
