# Generated by Django 5.2.9 on 2025-12-30 06:38

from django.conf import settings
from django.db import migrations, models


def assign_unique_priorities(apps, schema_editor):
    """Assign unique priorities to existing departments and services"""
    Department = apps.get_model('services', 'Department')
    Service = apps.get_model('services', 'Service')
    
    # Assign unique priorities to departments
    for index, dept in enumerate(Department.objects.all().order_by('id'), start=1):
        dept.priority = index
        dept.save()
    
    # Assign unique priorities to services
    for index, service in enumerate(Service.objects.all().order_by('id'), start=1):
        service.priority = index
        service.save()


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_department_departments_is_acti_a777bd_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['priority', 'title']},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['department__priority', 'priority', 'title']},
        ),
        # First add field without unique constraint
        migrations.AddField(
            model_name='department',
            name='priority',
            field=models.PositiveIntegerField(default=999, help_text='Display priority (lower number = higher priority, must be unique)'),
        ),
        migrations.AddField(
            model_name='service',
            name='priority',
            field=models.PositiveIntegerField(default=999, help_text='Display priority within department (lower number = higher priority, must be unique)'),
        ),
        # Run data migration to assign unique values
        migrations.RunPython(assign_unique_priorities, reverse_code=migrations.RunPython.noop),
        # Now alter field to add unique constraint
        migrations.AlterField(
            model_name='department',
            name='priority',
            field=models.PositiveIntegerField(default=999, help_text='Display priority (lower number = higher priority, must be unique)', unique=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='priority',
            field=models.PositiveIntegerField(default=999, help_text='Display priority within department (lower number = higher priority, must be unique)', unique=True),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['priority'], name='departments_priorit_784d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['priority'], name='services_priorit_8f45d8_idx'),
        ),
    ]
