# Generated by Django 5.2.9 on 2025-12-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_alter_department_options_alter_service_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricecard',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='discount_percentage',
            field=models.PositiveIntegerField(default=0, help_text='Discount percentage applied to all price cards in this service'),
        ),
    ]
