# Generated by Django 5.2.9 on 2026-04-05 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0011_pricecard_discounted_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricecard',
            name='discounted_price',
        ),
        migrations.RemoveField(
            model_name='pricecard',
            name='price',
        ),
        migrations.RemoveField(
            model_name='service',
            name='discount_percentage',
        ),
    ]
