# Generated by Django 5.2.9 on 2026-04-09 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0012_remove_price_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='logo',
        ),
    ]
