# Generated by Django 5.2.9 on 2026-04-09 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_remove_service_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='logo',
        ),
    ]
