# Generated by Django 5.2.9 on 2026-04-09 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_remove_department_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='departments/logos/'),
        ),
    ]
