# Generated by Django 5.2.9 on 2026-04-09 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0005_alter_media_owner'),
        ('services', '0015_department_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='hero_bg_desktop',
            field=models.ForeignKey(blank=True, help_text='Hero background for desktop view (Image or Video)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_desktop_heroes', to='media.media'),
        ),
        migrations.AddField(
            model_name='department',
            name='hero_bg_mobile',
            field=models.ForeignKey(blank=True, help_text='Hero background for mobile view (Image or Video)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='department_mobile_heroes', to='media.media'),
        ),
        migrations.AddField(
            model_name='department',
            name='hero_caption',
            field=models.CharField(blank=True, help_text='Optional caption to display on the hero section', max_length=255, null=True),
        ),
    ]
