# Generated by Django 6.0 on 2025-12-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_rename_assignee_id_task_assignee_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='attachments',
            field=models.JSONField(blank=True, default=list, help_text='List of Cloudinary URLs for task attachments'),
        ),
    ]
