# Generated by Django 5.2.9 on 2025-12-17 06:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(blank=True, max_length=255, unique=True)),
                ('excerpt', models.TextField(help_text='Short description for preview', max_length=500)),
                ('content', models.TextField(help_text='Full blog content (supports rich text)')),
                ('category', models.CharField(blank=True, max_length=100)),
                ('featured_image', models.URLField(blank=True, help_text='URL to featured image (Cloudinary)')),
                ('gallery_images', models.JSONField(blank=True, default=list, help_text='Array of image URLs')),
                ('tags', models.JSONField(blank=True, default=list, help_text='Array of tag strings')),
                ('is_published', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Blog Post',
                'verbose_name_plural': 'Blog Posts',
                'db_table': 'blogs',
                'ordering': ['-is_featured', '-published_at', '-created_at'],
            },
        ),
    ]
