# Generated by Django 5.2.9 on 2025-12-12 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_delete_specialoffer'),
        ('testimonials', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testimonial',
            name='client_role',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='testimonials', to='services.service'),
        ),
    ]
