# Generated by Django 5.2.9 on 2025-12-20 11:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_offer_imageurl'),
        ('payments', '0003_webhooklog_alter_transaction_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('gateway', models.CharField(choices=[('razorpay', 'Razorpay'), ('paypal', 'PayPal')], max_length=20)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('payment_link', models.URLField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_requests', to='orders.order')),
                ('payment_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_request', to='payments.paymentorder')),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payment_requests_created', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'payment_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['order'], name='payment_req_order_i_153392_idx'), models.Index(fields=['status'], name='payment_req_status_65728f_idx'), models.Index(fields=['requested_by'], name='payment_req_request_8abbbb_idx')],
            },
        ),
    ]
