# Generated by Django 5.2.9 on 2025-12-20 16:20
# Modified to properly handle existing data

import uuid
from django.db import migrations, models


def generate_unique_uuids_payments(apps, schema_editor):
    """Generate unique UUIDs for all existing payment records"""
    PaymentOrder = apps.get_model('payments', 'PaymentOrder')
    PaymentRequest = apps.get_model('payments', 'PaymentRequest')
    Transaction = apps.get_model('payments', 'Transaction')
    
    for obj in PaymentOrder.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save()
    
    for obj in PaymentRequest.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save()
    
    for obj in Transaction.objects.all():
        obj.uuid = uuid.uuid4()
        obj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentrequest'),
    ]

    operations = [
        # Step 1: Add UUID fields without unique constraint
        migrations.AddField(
            model_name='paymentorder',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='paymentrequest',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(db_index=True, editable=False, null=True),
        ),
        # Step 2: Populate UUIDs for existing records
        migrations.RunPython(generate_unique_uuids_payments, reverse_code=migrations.RunPython.noop),
        # Step 3: Make UUID non-nullable and unique
        migrations.AlterField(
            model_name='paymentorder',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='paymentrequest',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='uuid',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
