# Generated by Django 5.2.9 on 2025-12-29 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0005_paymentorder_uuid_paymentrequest_uuid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='receipt_pdf_dropbox_path',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='transaction',
            name='receipt_pdf_url',
            field=models.URLField(blank=True, max_length=500),
        ),
    ]
