# Generated by Django 6.0 on 2025-12-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='project_id',
            new_name='project',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='service_id',
            new_name='service',
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail_url',
            field=models.TextField(blank=True, null=True),
        ),
    ]
