# Generated by Django 6.0 on 2025-12-07 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_rename_owner_id_media_owner_and_more'),
        ('portfolio', '0003_portfolioproject_featured_image_and_more'),
        ('services', '0004_alter_department_logo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='media',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='portfolio.portfolioproject'),
        ),
        migrations.AlterField(
            model_name='media',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.service'),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumbnail_url',
            field=models.URLField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='url',
            field=models.URLField(),
        ),
    ]
