# Generated by Django 5.2.9 on 2025-12-13 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
        ('orders', '0011_estimation_invoice_orderstatushistory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceformsubmission',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission', to='orders.order'),
        ),
    ]
