# Generated by Django 5.2.9 on 2025-12-18 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_alter_serviceformsubmission_order'),
        ('services', '0008_service_team_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceform',
            name='card_type',
            field=models.CharField(choices=[('service', 'Service Card'), ('offer', 'Offer Card')], default='service', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceform',
            name='selected_offer_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='serviceform',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forms', to='services.service'),
        ),
    ]
