# Generated by Django 5.2.9 on 2025-12-31 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0003_serviceform_card_type_serviceform_selected_offer_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceformfield',
            name='field_type',
            field=models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('short_text', 'Short Text'), ('long_text', 'Long Text'), ('dropdown', 'Dropdown'), ('checkbox', 'Checkbox'), ('multi_select', 'Multi Select'), ('media', 'Media Upload'), ('date', 'Date')], max_length=20),
        ),
    ]
